export { default as Login } from './Login';
export { default as Dashboard } from './Dashboard';
export { default as Appointments } from './Appointments';
export { default as Services } from './Services';
export { default as Team } from './Team';
export { default as Testimonials } from './Testimonials';
export { default as FAQs } from './FAQs';
export { default as Gallery } from './Gallery';
export { default as Messages } from './Messages';
